
header-y +=


generic-y += barrier.h
generic-y += clkdev.h
generic-y += cputime.h
generic-y += irq_work.h
generic-y += mcs_spinlock.h
generic-y += preempt.h
generic-y += scatterlist.h
generic-y += sections.h
generic-y += trace_clock.h
generic-y += xor.h
generic-y += serial.h
generic-y += cacheflush.h
generic-y += checksum.h
generic-y += ftrace.h
generic-y += futex.h
generic-y += hardirq.h
